name: build

on:
  push:
    branches-ignore: [main]
  schedule:
    - cron: '0 * * * *' # Executar a cada hora
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2 # Action pré-existente do GitHub

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2 # Action pré-existente do GitHub
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore **/*.csproj

      - name: Build the webapp
        run: dotnet build **/*.csproj --no-restore
